//! `tomet cli-docs`: the CLI reference, written as a `.tmt`.
//!
//! The clap definitions are the one source. This walks them
//! (`clap::CommandFactory`), builds a [`Document`] -- one section per
//! subcommand, each with its usage, arguments and options -- prints it with
//! `tomet_printer` and runs the result through the formatter, so the file is
//! already what `tomet format --check` wants. The document is never built as
//! a string: help text is free prose, full of `@`, `[` and backticks, and the
//! printer is what knows how to write those back safely.
//!
//! The output is English, like the doc comments it comes from. Write it with
//! `--out`; `--check --out` fails when the file on disk is not what would be
//! written, which is how `just docs-check` catches a new flag nobody
//! regenerated the reference for.

use std::fs;
use std::path::{Path, PathBuf};

use clap::{Arg, Command, CommandFactory};
use tomet_ast::{
    Block, Document, Element, ElementValue, Entry, Inline, Paragraph, Placement, RawText, Section,
    Sigil, Span, Text, Value,
};
use tomet_config::PrinterConfig;
use tomet_tree::{ElementExt, element_new};

use crate::cli::Cli;

/// Where the reference is exported to, measured from the project root.
const EXPORT_PATH: &str = "docs/reference/cli.md";
const DOC_ID: &str = "doc-cliDocRf";
const NOTICE: &str = "Generated by `tomet cli-docs` from the clap definitions in \
     `apps/cli/src/cli.rs`. Do not edit it: change the doc comments there and run \
     the command again.";

pub(crate) fn cli_docs_cmd(out: Option<&Path>, check: bool) -> anyhow::Result<()> {
    let text = render(&config_for_output(out));

    let Some(out) = out else {
        print!("{text}");
        return Ok(());
    };

    if check {
        return match fs::read_to_string(out) {
            Ok(current) if current == text => Ok(()),
            Ok(_) => Err(anyhow::anyhow!(
                "{} is out of date; regenerate it with `tomet cli-docs --out {}`",
                out.display(),
                out.display()
            )),
            Err(e) => Err(anyhow::anyhow!(
                "cannot read {}: {e}; generate it with `tomet cli-docs --out {}`",
                out.display(),
                out.display()
            )),
        };
    }

    if let Some(parent) = out.parent().filter(|p| !p.as_os_str().is_empty()) {
        fs::create_dir_all(parent)?;
    }
    fs::write(out, text)?;
    println!("Wrote {}", out.display());
    Ok(())
}

/// The config that governs the output file, so the text is what `format
/// --check` accepts there.
fn config_for_output(out: Option<&Path>) -> PrinterConfig {
    let probe: PathBuf = out.map_or_else(|| PathBuf::from("."), Path::to_path_buf);
    tomet_config::find_config_file(&probe)
        .map_or_else(PrinterConfig::default, |(config, _, _)| config)
}

/// The whole reference, printed and formatted.
fn render(config: &PrinterConfig) -> String {
    let mut root = Cli::command();
    root.build();
    let doc = document(&mut root);
    let printed = tomet_printer::document_to_tm_with_config(&doc, config);
    tomet_formatter::format_source_with_config(&printed, config)
}

fn document(root: &mut Command) -> Document {
    let mut export = element_new(Sigil::named("config")).with_placement(Placement::Block);
    export.args = Some(Value::Map(vec![(
        "export".to_string(),
        Value::Map(vec![
            ("type".to_string(), Value::String("commonmark".to_string())),
            ("path".to_string(), Value::String(EXPORT_PATH.to_string())),
        ]),
    )]));

    let mut meta = element_new(Sigil::named("meta")).with_placement(Placement::Block);
    meta.value = Some(ElementValue::from_map(Value::Map(vec![(
        "id".to_string(),
        Value::String(DOC_ID.to_string()),
    )])));

    // Sections are laid out flat, siblings of the blocks they own, and the
    // parser nests them again when the file is read. `tomet-printer` puts a
    // blank line between top-level blocks only, so a paragraph nested in a
    // section would be printed against the next one and read back as one.
    let mut blocks = vec![Block::Element(export), Block::Element(meta)];
    push_command(root, 1, &mut blocks);
    // Right after the title of the reference.
    blocks.insert(3, paragraph(inlines(NOTICE)));

    Document::new(blocks, dummy())
}

/// One command as a section titled by its full name, then its blocks, then
/// its subcommands one level deeper.
fn push_command(cmd: &mut Command, level: usize, out: &mut Vec<Block>) {
    let name = cmd
        .get_bin_name()
        .map_or_else(|| cmd.get_name().to_string(), str::to_string);
    out.push(Block::Section(Section::new(
        level,
        vec![text(&name)],
        dummy(),
    )));

    let about = cmd
        .get_long_about()
        .or_else(|| cmd.get_about())
        .map(|s| s.to_string())
        .unwrap_or_default();
    for para in paragraphs(&about) {
        out.push(paragraph(inlines(&para)));
    }

    let usage = cmd.render_usage().to_string();
    let usage = usage.trim().strip_prefix("Usage:").unwrap_or(&usage).trim();
    out.push(Block::Element(code_block(usage)));

    let positional: Vec<&Arg> = cmd
        .get_arguments()
        .filter(|a| listed(a) && a.is_positional())
        .collect();
    let options: Vec<&Arg> = cmd
        .get_arguments()
        .filter(|a| listed(a) && !a.is_positional())
        .collect();
    if !positional.is_empty() {
        out.push(paragraph(vec![text("Arguments:")]));
        out.push(Block::Element(list(
            positional.iter().map(|a| item(cmd, a)),
        )));
    }
    if !options.is_empty() {
        out.push(paragraph(vec![text("Options:")]));
        out.push(Block::Element(list(options.iter().map(|a| item(cmd, a)))));
    }

    let subs: Vec<String> = cmd
        .get_subcommands()
        .filter(|s| s.get_name() != "help" && !s.is_hide_set())
        .map(|s| s.get_name().to_string())
        .collect();
    for sub in subs {
        if let Some(sub) = cmd.find_subcommand_mut(&sub) {
            push_command(sub, level + 1, out);
        }
    }
}

/// Arguments the reference lists: not clap's own `--help`/`--version`, not hidden.
fn listed(arg: &Arg) -> bool {
    !arg.is_hide_set() && !matches!(arg.get_id().as_str(), "help" | "version")
}

/// `` `-i, --in-place`: Overwrite the file(s). `` -- the argument's spelling
/// as code, then its help, its default and what it conflicts with.
fn item(cmd: &Command, arg: &Arg) -> Element {
    let mut content = vec![code(&label(arg))];

    let help = arg
        .get_long_help()
        .or_else(|| arg.get_help())
        .map(|s| s.to_string())
        .unwrap_or_default();
    let help = help.split_whitespace().collect::<Vec<_>>().join(" ");
    let mentions_default = help.to_lowercase().contains("default");
    if !help.is_empty() {
        let end = if help.ends_with(['.', '!', '?']) {
            ""
        } else {
            "."
        };
        content.extend(inlines(&format!(": {help}{end}")));
    }

    // A flag's `false` says nothing, and help that already states the
    // default (`defaults to "."`) should not be told it twice.
    let defaults: Vec<String> = arg
        .get_default_values()
        .iter()
        .map(|v| v.to_string_lossy().into_owned())
        .collect();
    if arg.get_action().takes_values() && !defaults.is_empty() && !mentions_default {
        content.push(text(" Default: "));
        content.push(code(&defaults.join(", ")));
        content.push(text("."));
    }

    let mut conflicts: Vec<String> = cmd
        .get_arg_conflicts_with(arg)
        .into_iter()
        .filter(|c| listed(c))
        .map(label_short)
        .collect();
    conflicts.sort();
    if !conflicts.is_empty() {
        content.push(text(" Conflicts with "));
        for (i, c) in conflicts.iter().enumerate() {
            if i > 0 {
                content.push(text(", "));
            }
            content.push(code(c));
        }
        content.push(text("."));
    }

    let mut el = element_new(Sigil::Bare).with_placement(Placement::Block);
    el.content = Some(content);
    el
}

/// How the argument is written: `<PATH>...`, `-i, --in-place`, `--out <OUT>`.
fn label(arg: &Arg) -> String {
    let value = arg
        .get_value_names()
        .and_then(|names| names.first().map(|n| n.to_string()))
        .unwrap_or_else(|| arg.get_id().as_str().to_uppercase());
    if arg.is_positional() {
        let many = arg.get_num_args().is_some_and(|r| r.max_values() > 1);
        let dots = if many { "..." } else { "" };
        return if arg.is_required_set() {
            format!("<{value}>{dots}")
        } else {
            format!("[{value}]{dots}")
        };
    }
    let mut names = Vec::new();
    if let Some(short) = arg.get_short() {
        names.push(format!("-{short}"));
    }
    if let Some(long) = arg.get_long() {
        names.push(format!("--{long}"));
    }
    let mut out = names.join(", ");
    if arg.get_action().takes_values() {
        out.push_str(&format!(" <{value}>"));
    }
    out
}

/// The argument's shortest spelling, for cross-references.
fn label_short(arg: &Arg) -> String {
    match (arg.get_long(), arg.get_short()) {
        (Some(long), _) => format!("--{long}"),
        (None, Some(short)) => format!("-{short}"),
        _ => label(arg),
    }
}

// --- AST helpers ----------------------------------------------------------

fn dummy() -> Span {
    Span::dummy()
}

fn text(s: &str) -> Inline {
    Inline::Text(Text::new(s, dummy()))
}

fn code(s: &str) -> Inline {
    let mut el = element_new(Sigil::named("raw")).with_placement(Placement::Inline);
    el.content = Some(vec![Inline::Raw(RawText::new(s, dummy()))]);
    Inline::Element(el)
}

fn paragraph(content: Vec<Inline>) -> Block {
    Block::Paragraph(Paragraph::new(content, dummy()))
}

fn code_block(body: &str) -> Element {
    let mut el = element_new(Sigil::named("raw")).with_placement(Placement::Block);
    el.args = Some(Value::Map(vec![(
        "lang".to_string(),
        Value::String("text".to_string()),
    )]));
    el.content = Some(vec![Inline::Raw(RawText::new(body, dummy()))]);
    el
}

fn list(items: impl Iterator<Item = Element>) -> Element {
    let mut el = element_new(Sigil::named("ul")).with_placement(Placement::Block);
    el.value = Some(ElementValue::Group(items.map(Entry::Element).collect()));
    el
}

/// Text with `` `code` `` spans turned into inline code. An unbalanced
/// backtick means it was not meant as one, so the text is kept as written.
///
/// Whatever could start an element -- `@config`, `@meta(format:yaml)`,
/// `${x}`, `^n(1)` -- is made code too. Inline text has no escape for those
/// and the printer writes a `Text` verbatim, so left as text they would come
/// back as elements when the file is read.
fn inlines(s: &str) -> Vec<Inline> {
    if !s.matches('`').count().is_multiple_of(2) {
        return vec![text(s)];
    }
    let mut out = Vec::new();
    for (i, part) in s.split('`').enumerate() {
        if part.is_empty() {
            continue;
        }
        if i % 2 == 1 {
            out.push(code(part));
        } else {
            out.extend(guard_triggers(part));
        }
    }
    out
}

/// Splits plain text so every element-looking word is a code span.
fn guard_triggers(s: &str) -> Vec<Inline> {
    let mut out = Vec::new();
    let mut plain = String::new();
    let mut rest = s;
    while let Some((at, c)) = rest
        .char_indices()
        .find(|&(i, c)| matches!(c, '@' | '$' | '^') && starts_element(&rest[i + c.len_utf8()..]))
    {
        plain.push_str(&rest[..at]);
        let word_end = rest[at..]
            .find(char::is_whitespace)
            .map_or(rest.len(), |n| at + n);
        let word = rest[at..word_end].trim_end_matches(['.', ',', ';', ':', '!', '?']);
        if !plain.is_empty() {
            out.push(text(&std::mem::take(&mut plain)));
        }
        out.push(code(word));
        rest = &rest[at + word.len()..];
        let _ = c;
    }
    plain.push_str(rest);
    if !plain.is_empty() {
        out.push(text(&plain));
    }
    out
}

/// What follows a sigil character when it opens an element: a name or a group.
fn starts_element(after: &str) -> bool {
    after
        .chars()
        .next()
        .is_some_and(|c| c.is_alphabetic() || matches!(c, '_' | '(' | '{'))
}

/// Blank-line separated paragraphs, each with its line wrapping folded away.
fn paragraphs(s: &str) -> Vec<String> {
    s.split("\n\n")
        .map(|p| p.split_whitespace().collect::<Vec<_>>().join(" "))
        .filter(|p| !p.is_empty())
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn rendered() -> String {
        render(&PrinterConfig::default())
    }

    #[test]
    fn every_subcommand_and_its_options_are_in_the_reference() {
        let text = rendered();
        let mut root = Cli::command();
        root.build();
        for sub in root.get_subcommands().filter(|s| s.get_name() != "help") {
            assert!(
                text.contains(&format!("tomet {}", sub.get_name())),
                "missing section for `{}`",
                sub.get_name()
            );
        }
        // A flag added in this task, as a spot check that arguments come through.
        assert!(text.contains("--force"), "options are listed");
    }

    #[test]
    fn the_output_is_valid_tmt_and_already_formatted() {
        let text = rendered();
        tomet_parser::parse_document(&text).expect("the generated reference parses");
        assert_eq!(
            tomet_formatter::format_source_with_config(&text, &PrinterConfig::default()),
            text,
            "`tomet format --check` must accept the generated file"
        );
    }

    #[test]
    fn reading_the_output_back_keeps_every_paragraph_and_section() {
        // The regression this guards is structural: two paragraphs printed
        // on adjacent lines parse as one, and nothing else would notice.
        fn count(blocks: &[Block], sections: &mut usize, paragraphs: &mut usize) {
            for block in blocks {
                match block {
                    Block::Section(s) => {
                        *sections += 1;
                        count(&s.blocks, sections, paragraphs);
                    }
                    Block::Paragraph(_) => *paragraphs += 1,
                    Block::Element(_) => {}
                }
            }
        }
        let mut root = Cli::command();
        root.build();
        let (mut want_s, mut want_p) = (0, 0);
        count(&document(&mut root).blocks, &mut want_s, &mut want_p);

        let parsed = tomet_parser::parse_document(&rendered()).unwrap();
        let (mut got_s, mut got_p) = (0, 0);
        count(&parsed.blocks, &mut got_s, &mut got_p);
        assert_eq!((got_s, got_p), (want_s, want_p));
    }

    #[test]
    fn the_output_is_deterministic() {
        assert_eq!(rendered(), rendered());
    }

    #[test]
    fn check_reports_a_missing_stale_and_current_file() {
        let dir = std::env::temp_dir().join(format!("tomet_test_cli_docs_{}", nanoid::nanoid!()));
        let out = dir.join("generated").join("cli.tmt");

        assert!(cli_docs_cmd(Some(&out), true).is_err(), "missing");

        cli_docs_cmd(Some(&out), false).unwrap();
        assert!(cli_docs_cmd(Some(&out), true).is_ok(), "current");

        fs::write(&out, "stale\n").unwrap();
        assert!(cli_docs_cmd(Some(&out), true).is_err(), "stale");

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn text_that_looks_like_an_element_stays_text_when_read_back() {
        // `@meta(format:yaml)` in a help string once came back as a second
        // `@meta` element and failed `tomet check`.
        fn stray(inlines: &[Inline], found: &mut Vec<String>) {
            for inline in inlines {
                if let Inline::Element(el) = inline
                    && !el.sigil.is_bare_named("raw")
                {
                    found.push(format!("{:?}", el.sigil));
                }
            }
        }
        fn walk(blocks: &[Block], found: &mut Vec<String>) {
            for block in blocks {
                match block {
                    Block::Paragraph(p) => stray(&p.content, found),
                    Block::Section(s) => walk(&s.blocks, found),
                    Block::Element(el) => {
                        stray(el.content.as_deref().unwrap_or(&[]), found);
                        if let Some(ElementValue::Group(entries)) = &el.value {
                            for entry in entries {
                                if let Entry::Element(item) = entry {
                                    stray(item.content.as_deref().unwrap_or(&[]), found);
                                }
                            }
                        }
                    }
                }
            }
        }
        let parsed = tomet_parser::parse_document(&rendered()).unwrap();
        let mut found = Vec::new();
        walk(&parsed.blocks, &mut found);
        assert!(found.is_empty(), "text came back as elements: {found:?}");

        assert_eq!(guard_triggers("Overrides @config.").len(), 3);
        assert_eq!(
            guard_triggers("cost $5 or a@ b").len(),
            1,
            "not element-like"
        );
    }

    #[test]
    fn backticks_become_inline_code_and_an_odd_one_stays_text() {
        assert_eq!(inlines("a `b` c").len(), 3);
        assert_eq!(inlines("it`s").len(), 1);
    }
}
