[workspace]
resolver = "3"

members = [
  #[ CLI & Web ]
  "apps/typedmark",
  "apps/typedmark-web",
  "apps/typedmark-lsp",

  #[ Bindings ]
  "apps/bindings/java",
  "apps/bindings/js",
  "apps/bindings/python",

  #[ Editor Support ]
  "apps/integrations/zed",
  "apps/integrations/neovim",
  "apps/integrations/helix",

  #[ Core ]
  "crates/typedmark-ast",
  "crates/typedmark-walk",
  "crates/typedmark-lexar",
  "crates/typedmark-parser",
  "crates/typedmark-semantics",
  "crates/typedmark-resolve",
  "crates/typedmark-validator",

  #[ Converter ]
  "crates/converters/markdown",
  "crates/converters/html",

  #[ Consumer ]
  "crates/typedmark-formatter",
  "crates/serde_typedmark",
  "crates/tree-sitter-typedmark",
  "crates/typedmark-compute",
]

default-members = ["apps/typedmark"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
typedmark-ast = { path = "crates/typedmark-ast" }
typedmark-walk = { path = "crates/typedmark-walk" }
typedmark-lexar = { path = "crates/typedmark-lexar" }
typedmark-parser = { path = "crates/typedmark-parser" }
typedmark-semantics = { path = "crates/typedmark-semantics" }
typedmark-resolve = { path = "crates/typedmark-resolve" }
typedmark-validator = { path = "crates/typedmark-validator" }
typedmark-formatter = { path = "crates/typedmark-formatter" }
serde_typedmark = { path = "crates/serde_typedmark" }
#[ Converter ]
typedmark-markdown = { path = "crates/converters/markdown" }
typedmark-html = { path = "crates/converters/html" }

#[ Crates.io ]
anyhow = "1"
axum = { version = "0.8", default-features = false, features = [
  "http1",
  "tokio",
] }
clap = { version = "4.6", features = ["derive"] }
cxx = "1"
crossterm = "0.28"
directories = "6.0"
lsp-server = "0.10"
lsp-types = "0.97"
pulldown-cmark = "0.13"
ratatui = "0.29"
rayon = "1"
regex = "1.12"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
serde_yaml = "0.9"
time = "0.3"
tokio = "1"
toml = { version = "0.9", features = ["preserve_order"] }
tree-sitter = "0.26"
tree-sitter-language = "0.1"
uuid = { version = "1.23", features = ["v4"] }
walkdir = "2"
zed_extension_api = "0.7"
