[workspace]
resolver = "3"

members = [
  #[ CLI ]
  "apps/typedmark",
  #[ Language Support ]
  "apps/typedmark-java",
  "apps/typedmark-js",
  "apps/typedmark-lsp",
  "apps/typedmark-python",
  #[ Editor Support ]
  "apps/zed-extension",
  "apps/vscode-extension",
  "apps/neovim-plugin",
  "apps/helix-plugin",

  "crates/typedmark-ast",
  "crates/typedmark-lexar",
  "crates/typedmark-parser",
  "crates/typedmark-validator",
  "crates/typedmark-markdown",
  "crates/typedmark-renderer",
  "crates/typedmark-formatter",
  "crates/serde_typedmark",
  "crates/tree-sitter-typedmark"
]

default-members = [
  "apps/typedmark"
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
typedmark-ast = { path = "crates/typedmark-ast" }
typedmark-formatter = { path = "crates/typedmark-formatter" }
typedmark-lexar = { path = "crates/typedmark-lexar" }
typedmark-markdown = { path = "crates/typedmark-markdown" }
typedmark-parser = { path = "crates/typedmark-parser" }
typedmark-renderer = { path = "crates/typedmark-renderer" }
serde_typedmark = { path = "crates/serde_typedmark" }

#[ Crates.io ]
anyhow = "1"
axum = { version = "0.8", default-features = false, features = ["http1", "tokio"] }
clap = { version = "4.6", features = ["derive"] }
cxx = "1"
directories = "6.0"
lsp-server = "0.10"
lsp-types = "0.97"
pulldown-cmark = "0.13"
rayon = "1"
regex = "1.12"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
serde_yaml = "0.9"
time = "0.3"
tokio = "1"
toml = { version = "0.9", features = ["preserve_order"] }
tree-sitter = "0.26"
tree-sitter-language = "0.1"
uuid = { version = "1.23", features = ["v4"] }
walkdir = "2"
zed_extension_api = "0.7"
