[package]
name = "tomet-java"
version.workspace = true
edition.workspace = true

[lib]
name = "tomet_java"
crate-type = ["cdylib", "rlib"]

[dependencies]
tomet = { workspace = true, features = ["html", "markdown", "typst", "format", "printer"] }

jni = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
