[package]
name = "typedmark-printer"
version.workspace = true
edition.workspace = true

[dependencies]
typedmark-ast = { workspace = true }
typedmark-config = { workspace = true }
typedmark-field-utils = { workspace = true }
typedmark-formatter = { workspace = true }
typedmark-semantics = { workspace = true }
typedmark-style = { workspace = true }

[dev-dependencies]
typedmark-markdown = { workspace = true }
typedmark-parser = { workspace = true }
