[package]
name = "typedmark-markdown"
version.workspace = true
edition.workspace = true

[dependencies]
pulldown-cmark = { workspace = true }
serde_yaml = { workspace = true }
typedmark-ast = { workspace = true }
typedmark-semantics = { workspace = true }

[dev-dependencies]
typedmark-html = { workspace = true }
