name = "Tomet"
grammar = "tomet"
path_suffixes = ["tm", "tmt"]
line_comment = "//"
block_comment = ["/*", "*/"]

[[brackets]]
start = "{"
end = "}"
close = true
newline = true

[[brackets]]
start = "["
end = "]"
close = true
newline = true

[[brackets]]
start = "("
end = ")"
close = true
newline = true
