[package]
name = "tomet-tui"
version.workspace = true
edition.workspace = true

[dependencies]
tomet-ast = { workspace = true }
tomet-config = { workspace = true }
tomet-indexer = { workspace = true }
tomet-markdown = { workspace = true }
tomet-parser = { workspace = true }
tomet-printer = { workspace = true }
tomet-semantics = { workspace = true }
tomet-transform = { workspace = true }
tomet-tree = { workspace = true }
tomet-workspace = { workspace = true }
tree-sitter-tomet = { workspace = true }

#[ Crates.io ]
anyhow = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }
tree-sitter = { workspace = true }

[dev-dependencies]
uuid = { workspace = true }
