[package]
name = "tomet-printer"
version.workspace = true
edition.workspace = true

[dependencies]
tomet-ast = { workspace = true }
tomet-config = { workspace = true }
tomet-field-utils = { workspace = true }
tomet-formatter = { workspace = true }
tomet-semantics = { workspace = true }
tomet-style = { workspace = true }
tomet-tree = { workspace = true }

#[ Crates.io ]
serde_json = { workspace = true }
serde_yaml = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
tomet-markdown = { workspace = true }
tomet-parser = { workspace = true }
