[package]
name = "typedmark-lsp"
version.workspace = true
edition.workspace = true

[[bin]]
name = "typedmark-lsp"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
lsp-server = { workspace = true }
lsp-types = { workspace = true }
serde_json = { workspace = true }
typedmark-formatter = { workspace = true }
typedmark-parser = { workspace = true }
