[package]
name = "tomet-ast"
version.workspace = true
edition.workspace = true
description = "Shared AST and Value data models for the Tomet toolchain."
license.workspace = true
repository.workspace = true

[dependencies]
tomet-cst = { workspace = true }

#= Crates.io
serde = { workspace = true }
unicode-width = { workspace = true }
