[package]
name = "tomet"
version.workspace = true
edition.workspace = true

[features]
format = ["dep:tomet-formatter"]
html = ["dep:tomet-html"]
markdown = ["dep:tomet-markdown"]
pandoc = ["dep:tomet-pandoc"]
printer = ["dep:tomet-printer"]
typst = ["dep:tomet-typst"]

[dependencies]
tomet-ast = { workspace = true }
tomet-config = { workspace = true }
tomet-load = { workspace = true }
tomet-parser = { workspace = true }
tomet-semantics = { workspace = true }
tomet-validator = { workspace = true }
tomet-vault = { workspace = true }

#= Optional
tomet-formatter = { workspace = true, optional = true }
tomet-html = { workspace = true, optional = true }
tomet-markdown = { workspace = true, optional = true }
tomet-pandoc = { workspace = true, optional = true }
tomet-printer = { workspace = true, optional = true }
tomet-typst = { workspace = true, optional = true }
