[package]
name = "typedmark-links"
version.workspace = true
edition.workspace = true

[dependencies]
typedmark-ast = { workspace = true }
typedmark-config = { workspace = true }
typedmark-indexer = { workspace = true }
typedmark-parser = { workspace = true }
typedmark-semantics = { workspace = true }
typedmark-walker = { workspace = true }

#[ Crates.io ]
rusqlite = { workspace = true }

[dev-dependencies]
uuid = { workspace = true }
