[package]
name = "typedmark-edit"
version.workspace = true
edition.workspace = true

[dependencies]
typedmark-ast = { workspace = true }
typedmark-config = { workspace = true }
typedmark-indexer = { workspace = true }
typedmark-parser = { workspace = true }
typedmark-printer = { workspace = true }
typedmark-semantics = { workspace = true }
typedmark-walker = { workspace = true }

#[ Crates.io ]
anyhow = { workspace = true }
