[package]
name = "tomet-markdown"
version.workspace = true
edition.workspace = true

[dependencies]
tomet-ast = { workspace = true }
tomet-semantics = { workspace = true }
tomet-tree = { workspace = true }

#[ Crates.io ]
pulldown-cmark = { workspace = true }
serde_yaml = { workspace = true }
nanoid = { workspace = true }

[dev-dependencies]
tomet-html = { workspace = true }
