[package]
name = "tomet-load"
version.workspace = true
edition.workspace = true

[dependencies]
tomet-ast = { workspace = true }
tomet-config = { workspace = true }
tomet-indexer = { workspace = true }
tomet-parser = { workspace = true }
tomet-resolver = { workspace = true }
tomet-compute = { workspace = true }
tomet-semantics = { workspace = true }
tomet-transform = { workspace = true }
