const esbuild = require("esbuild");

const watch = process.argv.includes("--watch");

const options = {
	entryPoints: ["src/main.ts"],
	bundle: true,
	// Self-contained (never writes outside this directory): the nix
	// packaging build (`nix/pkgs/typedmark-web.nix`) sandboxes this npm
	// project's own build to just `apps/web/frontend`, so a `../static`
	// outfile silently has nowhere real to land there. `npm run
	// build:local` copies `dist/app.js` into `../static/app.js` for local
	// `cargo run -p typedmark-web` use; the nix derivation does the
	// equivalent copy itself, from its own build output.
	outfile: "dist/app.js",
	format: "iife",
	platform: "browser",
	target: "es2020",
	minify: !watch,
	banner: {
		js: "// Generated by apps/web/frontend (esbuild) -- do not edit directly, edit apps/web/frontend/src/*.ts instead.",
	},
};

async function main() {
	if (watch) {
		const ctx = await esbuild.context(options);
		await ctx.watch();
	} else {
		await esbuild.build(options);
	}
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
