[package]
name = "tomet-parser"
version.workspace = true
edition.workspace = true

[dependencies]
tomet-ast = { workspace = true }
tomet-lexar = { workspace = true }

#[ Crates.io ]
serde_json = { workspace = true }
serde_yaml = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
tomet-semantics = { workspace = true }
