[package]
name = "tomet-parser"
version.workspace = true
edition.workspace = true

[dependencies]
tomet-ast = { workspace = true }
tomet-cst = { workspace = true }
tomet-lexer = { workspace = true }
tomet-tree = { workspace = true }
tove = { workspace = true }

#[ Crates.io ]
unicode-width = { workspace = true }

[dev-dependencies]
tomet-semantics = { workspace = true }
