[package]
name = "tomet-js"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
tomet = { workspace = true, features = ["html", "markdown", "typst", "format", "printer"] }
tomet-cst = { workspace = true }
tomet-lexer = { workspace = true }
tomet-links = { workspace = true }
tomet-transform = { workspace = true }

wasm-bindgen = { workspace = true }
serde-wasm-bindgen = { workspace = true }
serde = { workspace = true }
js-sys = { workspace = true }
getrandom = { version = "0.2", features = ["js"] }
regex = { workspace = true }
