[package]
name = "typedmark-printer"
version.workspace = true
edition.workspace = true

[dependencies]
typedmark-ast = { workspace = true }
typedmark-formatter = { workspace = true }
typedmark-parser = { workspace = true }
typedmark-semantics = { workspace = true }

#[ Crates.io ]
nanoid = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
typedmark-markdown = { workspace = true }
