- <T()>はどう？
- --advancedでserveした場合に、色々試せるように、設定をGUI経由でできるようにする（html出力はそのままで。）
  - urlを何らかの方法で見えるようにする。
- <var>(boolean){ bool1:true, }
- ${var} or {{var}}
  - これ、もしかして共通記法じゃないか？
  - $と{}で。しかし共通の場合、$()じゃないか？
- アウトライン記法をもっともっと練りたい。
- @tag(unko)
  - @{unko}省略できるのでは？
- <index>(){}
- <template>
- <time>
- 後方互換性
  - 知らない @xxx を見ても、パーサー全体を壊さない
- 「とりあえずdivで包める」みたいな汎用コンテナをTypedMarkに大量導入すると、せっかくの@linkや@codeの意味が薄くなる。
- Markdownの簡潔さ + HTMLのsemantic structure + ASTとしての厳格さ
