[package]
name = "tomet-edit"
version.workspace = true
edition.workspace = true

[dependencies]
tomet-ast = { workspace = true }
tomet-config = { workspace = true }
tomet-indexer = { workspace = true }
tomet-parser = { workspace = true }
tomet-printer = { workspace = true }
tomet-semantics = { workspace = true }
tomet-walker = { workspace = true }

#[ Crates.io ]
anyhow = { workspace = true }
