[package]
name = "tomet-lsp"
version.workspace = true
edition.workspace = true

[[bin]]
name = "tomet-lsp"
path = "src/main.rs"

[dependencies]
tomet-ast = { workspace = true }
tomet-compute = { workspace = true }
tomet-config = { workspace = true }
tomet-cst = { workspace = true }
tomet-formatter = { workspace = true }
tomet-parser = { workspace = true }
tomet-resolver = { workspace = true }
tomet-semantics = { workspace = true }
tomet-tree = { workspace = true }
tomet-validator = { workspace = true }

#[ Crates.io ]
anyhow = { workspace = true }
lsp-server = { workspace = true }
lsp-types = { workspace = true }
serde_json = { workspace = true }
